---
# ------------------------------------------------------------------------
# tasks file for ufw
# ------------------------------------------------------------------------

- name: install ufw
  package:
    name: "{{ ufw_packages }}"
    state: present
  register: ufw_install_ufw
  until: ufw_install_ufw is succeeded
  retries: 3


# ------------------------------------------------------------------------
# configure ufw
# ------------------------------------------------------------------------

- name: reset ufw
  ufw:
    state: reset
  tags:
    - molecule-idempotence-notest

- name: restart ufw
  service:
    name: ufw
    state: restarted
  tags:
    - molecule-idempotence-notest

- name: configure ufw defaults
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  with_items:
    - {direction: "incoming", policy: "{{ ufw_def_incoming }}"}
    - {direction: "outgoing", policy: "{{ ufw_def_outgoing }}"}

# Not working in Docker tests https://github.com/moby/moby/issues/33605
- name: configure ufw rules
  ufw:
    rule: "{{ item.rule }}"
    direction: "{{ item.direction }}"
    proto: "{{ item.proto }}"
    port: "{{ item.port }}"
  with_items:
    - "{{ ufw_rules }}"
  when:
    - ansible_connection != "docker"

# ------------------------------------------------------------------------
# enable ufw
# ------------------------------------------------------------------------

# see: https://github.com/ansible/ansible/issues/45446
- name: Configure the kernel to keep connections alive when enabling the firewall
  sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: "1"
    state: present
    sysctl_set: true
    reload: true
  when:
    - ansible_connection != "docker"

- name: enable ufw
  ufw:
    state: enabled
  when:
    - ansible_connection != "docker"

- name: restart ufw
  service:
    name: ufw
    state: restarted
  tags:
    - molecule-idempotence-notest
